### ISSUE TITLE
sfAndTotalCounts not present in $WDIR

### ISSUE THREAD

**Issue by wojtuch** [dbpedia-spotlight/model-quickstarter#12]
This fork of model-quickstarter announces not using Hadoop and Pig scripts anymore.

However, the cloned spotlight [still wants to read](https://github.com/dbpedia-spotlight/dbpedia-spotlight-model/blob/master/index/src/main/scala/org/dbpedia/spotlight/db/CreateSpotlightModel.scala#L186) the file `$WDIR/sfAndTotalCounts` but the current version of `index_db.sh` doesn't generate it anymore (as opposed to [the old one](https://raw.githubusercontent.com/jodaiber/dbpedia-spotlight/master/bin/index_db.sh)).

How can one address this problem?

**Comment by jodaiber** [comment]
Hi @wojtuch,

`sfAndTotalCounts` is one of the files produced by `wikistatsextractor `, which replaces the pignlproc pipeline. Did you get an error when running the script?

Jo

**Comment by wojtuch** [comment]
Hi @jodaiber, thanks for the answer.
I have made a clean installation of the components and now I was able to run everything smoothly, the required file was there.
As for now we can close the issue I suppose, if I ever run into it again, I'd investigate as much as I can and post here.

wojtuch
