### ISSUE TITLE
Question about data

### ISSUE THREAD

**Issue by meitals** [dbpedia-spotlight/model-quickstarter#8]
If I use model-quickstarter to create an English model, when will the data be from?

**Comment by sandroacoelho** [comment]
Hi @meitals,

You can run it in two ways:

  - without map volumes: the data will be inside the container
  - map volumes: the data will be in the host

E.g:
```
docker run -v /home/user/data/model/wdir:/model-quickstarter/wdir -v /home/user/data/model/data:/model-quickstarter/data -v /home/user/data/model/models:/model-quickstarter/models -it dbpediaspotlight/model-quickstarter bash
```

Best,
